### ISSUE TITLE
Loop back to the IdP home page

### ISSUE THREAD

**Issue by lghinelli-git** [dmirandaa/moodle-auth_saml2sso#39]
**Describe the bug**

If I use the simplesamlphp test, everything works fine I can see user attributes, vice versa if I using Moodle page, after authentication, which is successful, I loop back to the IdP home page.

**Comment by mfprimo** [comment]
Hi,
  thank you for the report.

The SimpleSAMLphp test page is the one under the "Test authentication sources" tab?
Can you report the Moodle saml plugin config?

**Comment by lghinelli-git** [comment]
Hello Marco,
yes, the SimpleSAMLphp test page is the one under the "Test authentication sources" tab and it works fine.

Moodle saml plugin config

SimpleSAMLphp library path: /var/simplesamlphp/
SP auth source name:Lepida
Single Sign Off: No
Logout URL: Empty
Username attribute:emailAddressPersonale
Username checking: Email address
Auto create users: Yes (or No nothing changes)
Dual login: Yes
No Users sync
SAML attributes and user profile: Nothingh set

Test authentication settings - SAML2 SSO Auth
SimpleSAMLphp version is 1.19.0-rc1
It seems SimpleSAMLphp uses default PHP session storage, it could be troublesome: switch to another store.type in config.php
Everything seems ok

**Comment by lghinelli-git** [comment]
Hello Marco,
I used SAML DevTools extension to debug what happens, after the POST
**both**
Request URL: https://vmmoodlesp.greenteam.online/simplesaml/module.php/saml/sp/saml2-acs.php/Lepida
Request Method: POST
Status Code: 303 See Other
**SimpleSAMLphp:**
Request URL: https://vmmoodlesp.greenteam.online/simplesaml/module.php/core/authenticate.php?as=Lepida
Request Method: GET
Status Code: 200 OK
**auth_saml2sso:**
Request URL: https://vmmoodlesp.greenteam.online/moodle2/login/index.php?saml=on
Request Method: GET
Status Code: 302 Found
Location: https://federatest.lepida.it/gw/SSOProxy/SAML2?xxxxxxxxx

Does it help?

**Comment by mfprimo** [comment]
Sorry for the delay.
I couldn't replicate the problem, I suspect it is a sessin-related issue. Try to replace the session handler of SimpleSAMLphp with someone other than phpsession.
(se ho capito correttamente che sei italiano, possiamo sentirci per telefono, mi trovi sulla rubrica dell'università)

**Comment by lghinelli-git** [comment]
Grazie,
provo a cambiare il gestore delle sessione intanto.

**Comment by lghinelli-git** [comment]
SOLVED!
in /var/simplesamlphp/config/config.php, changed store.type from 'phpsession' to 'memcache', now during logon session a debug message appear 'There is no valid e-mail address from Identity Provider, changed the setting 'Allow empty email' form 'No' to 'Yes' and now I can login into Moodle using SAML IdP.
