### ISSUE TITLE
SimpleSAML_Error_NoState: NOSTAT

### ISSUE THREAD

**Issue by cvnniranjanreddy** [dmirandaa/moodle-auth_saml2sso#6]
Hi,
We are trying this plugin in Moodle3.1 and we configured simplesamlphp as per instructions given and everything working fine via simplesamlphp tests works. But when we try to login via Moodle it is showing below error. 
SimpleSAML_Error_NoState: NOSTATE
Backtrace:
2 /opt/rh/httpd24/root/var/simplesamlphp/lib/SimpleSAML/Auth/State.php:263 (SimpleSAML_Auth_State::loadState)
1 /opt/rh/httpd24/root/var/simplesamlphp/modules/saml/www/sp/saml2-acs.php:78 (require)
0 /opt/rh/httpd24/root/var/simplesamlphp/www/module.php:137 (N/A)

Can you please help us identifying the issue. Please let me know what confurations that I need to cross check to fix the issue..

**Comment by mfprimo** [comment]
It's not a issue specific of this plugin: interaction between sessions managed by SimpleSAMLphp and those handled by Moodle is troublesome and requires some tuning:
https://simplesamlphp.org/docs/development/simplesamlphp-nostate
Probably, the easier solution it is to set a session storage other than the default PHP session files.
Check the value of 'store.type' in SimpleSAMLphp config.php file and change it if it is 'phpsession'
